### ISSUE TITLE
Error when running benchmark with pytorch-cpu

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [ToriML/DNN-bench#4]
Hi,

When running benchmark on CPU with the following command: `./bench_model.sh ./stsb-xlm-r-multilingual.bert.opt.onnx --repeat=100 --number=1 --warmup=10 --device=cpu --tf --onnxruntime --openvino --pytorch --nuphar`, I got the following error regarding pytorch:

```
PyTorch
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/bench/__main__.py", line 80, in <module>
    args.quantize,
  File "/bench/__main__.py", line 21, in main
    model = ConvertModel(onnx_model)
  File "/opt/conda/lib/python3.7/site-packages/onnx2pytorch/convert/model.py", line 63, in __init__
    for op_id, op_name, op in convert_operations(onnx_model, batch_dim):
  File "/opt/conda/lib/python3.7/site-packages/onnx2pytorch/convert/operations.py", line 168, in convert_operations
    "Conversion not implemented for op_type={}.".format(node.op_type)
NotImplementedError: Conversion not implemented for op_type=Not.
```

And I got the same error when running with pytorch-gpu

Would you have an idea of the problem?

Thanks,
Matthieu

**Comment by Talmaj** [comment]
Hi, this is a problem of `op_type=Not` not being implemented in [onnx2pytorch](https://github.com/ToriML/onnx2pytorch). 
The onnx model is converted by this library to pytorch version. 
Feel free to re-open the issue there or propose a pull request.
